<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Summer Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Data analysis with house sales data.</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Koulika Paul<br>
  <strong>Designation:</strong> Project Linked Associate Research Engineer in Statistics
</blockquote>
<hr style="width:100%;">
</div>

### Question 1: Import Libraries and Load Data (2 Marks)

Import `pandas` as `pd` and `numpy` as `np`. Download the data `house_price_india.csv` from https://drive.google.com/drive/folders/1gieHICVDBbUKMZiSF4YRQMAJic-w50JM?usp=sharing and load the dataset into a DataFrame called `house_data` and display its first 5 rows.

**Expected Output:** A table showing the first 5 rows of the house price dataset.

In [ ]:
import io
import pandas as pd
from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
    df = pd.read_csv(io.BytesIO(uploaded[filename]))

print("  preview of data:")
df.head()

Saving house_price_india (1).csv to house_price_india (1) (4).csv
  preview of data:

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

### Question 2: Data Inspection (2 Marks)

Inspect the `house_data` DataFrame. Print its shape to see the number of rows and columns, and then check for the total number of duplicate rows in the dataset.

**Expected Output:** The shape of the DataFrame (e.g., `(14620, 23)`) and the total count of duplicate rows.

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(14620, 23)

### Question 3: Data Types and Missing Values (1 Marks)

Display the data types of all columns in the `house_data` DataFrame. Then, calculate and print the total number of missing (null) values for each column.

**Expected Output:** A list of columns with their data types, followed by a list of columns and their respective missing value counts.

In [ ]:
missing_data=df.isnull().sum().sort_values(ascending=False)
missing_data

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

### Question 4: Column Cleanup (1 Marks)

Drop the following columns from the `house_data` DataFrame as they are not needed for this analysis: 'Date', 'Longitude', 'Renovation Year', 'Postal Code', 'Lattitude', 'living_area_renov', 'lot_area_renov'. Print the remaining columns.

**Expected Output:** A printed Index object showing the list of remaining column names.

In [ ]:
df_clean=df.drop(['Date','Longitude','Renovation Year','Postal Code','Lattitude','living_area_renov','lot_area_renov'],axis=1)
remaining_columns=df_clean.columns
print(remaining_columns)

Index(['id', 'number of bedrooms', 'number of bathrooms', 'living area',
       'lot area', 'number of floors', 'waterfront present', 'number of views',
       'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Number of schools nearby', 'Distance from the airport',
       'Price'],
      dtype='object')

### Question 5: Descriptive Statistics (1 Marks)

Generate and display the descriptive statistics for only the numerical columns of the cleaned `house_data` DataFrame.

**Expected Output:** A table showing count, mean, std, min, 25%, 50%, 75%, and max for the numerical columns.

In [ ]:
df_clean.describe()

,id,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Number of schools nearby,Distance from the airport,Price
count,1.462000e+04,14620.000000,14620.000000,14620.000000,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04
mean,6.762821e+09,3.379343,2.129583,2098.262996,1.509328e+04,1.502360,0.007661,0.233105,3.430506,7.682421,1801.783926,296.479070,1970.926402,2.012244,64.950958,5.389322e+05
std,6.237575e+03,0.938719,0.769934,928.275721,3.791962e+04,0.540239,0.087193,0.766259,0.664151,1.175033,833.809963,448.551409,29.493625,0.817284,8.936008,3.675324e+05
min,6.762810e+09,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,4.000000,370.000000,0.000000,1900.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,3.000000,1.750000,1440.000000,5.010750e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1200.000000,0.000000,1951.000000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1580.000000,0.000000,1975.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2240.000000,580.000000,1997.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,3.000000,80.000000,7.700000e+06

### Question 6: Group by Bedrooms (1 Marks)

Group the `house_data` DataFrame by the 'number of bedrooms' and calculate the average price for each group. Display the resulting Series.

**Expected Output:** A Pandas Series with the number of bedrooms as the index and the average price as the values.

In [ ]:
bedroom_group = df_clean.groupby('number of bedrooms')['Price'].mean()
print(bedroom_group)

number of bedrooms
1     3.089638e+05
2     3.985476e+05
3     4.632776e+05
4     6.361988e+05
5     7.752550e+05
6     8.375815e+05
7     1.016544e+06
8     1.208455e+06
9     7.766663e+05
10    8.200000e+05
11    5.200000e+05
33    6.400000e+05
Name: Price, dtype: float64

### Question 7: Houses with Waterfront (1 Marks)

Calculate the total number of houses that have a waterfront view. Then, calculate the average price of houses with a waterfront view versus those without.

**Expected Output:** The count of houses with and without waterfronts, followed by their average prices.

In [ ]:
print("Waterfront counts:")
print(df_clean['waterfront present'].value_counts())
print("\nAverage prices:")
print(df_clean.groupby('waterfront present')['Price'].mean())

Waterfront counts:
waterfront present
0    14508
1      112
Name: count, dtype: int64

Average prices:
waterfront present
0    5.304174e+05
1    1.641902e+06
Name: Price, dtype: float64

### Question 8: Feature Selection based on Correlation (2 Marks)

Calculate the correlation of all numerical features with the 'Price' column. Create a list named `highly_correlated_features` containing the names of features that have a correlation with 'Price' greater than 0.5. Print this list.

**Hint:** First calculate the full correlation matrix with `.corr()`. Then, select the 'Price' column from it. Filter this series to find features where the correlation value is > 0.5 and get their index.

**Expected Output:** A list of strings, where each string is the name of a highly correlated feature.

In [ ]:
numerical_df= df_clean.select_dtypes(include=['number'])
correlation_matrix = numerical_df.corr()
price_correlation = correlation_matrix['Price']
highly_correlated_series = price_correlation[(price_correlation > 0.5) & (price_correlation.index != 'Price')]
highly_correlated_features = list(highly_correlated_series.index)
print(highly_correlated_features)

['number of bathrooms', 'living area', 'grade of the house', 'Area of the house(excluding basement)']

### Question 9: Prepare Data for Modeling (1 Marks)

Using the `highly_correlated_features` list from the previous question, create your feature matrix `X`. Your target vector `y` should be the 'Price' column. Then, split `X` and `y` into training and testing sets with a `test_size` of 0.3 and a `random_state` of 123.

**Expected Output:** No direct output. The variables `X_train`, `X_test`, `y_train`, and `y_test` will be created.

In [ ]:
from sklearn.model_selection import train_test_split
X = df_clean[highly_correlated_features]
y = df_clean['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

### Question 10: Train and Evaluate a Linear Regression Model (5 Marks)

Import `LinearRegression` from `sklearn.linear_model` and `r2_score` from `sklearn.metrics`. Train a linear regression model on your training data. Make predictions on the test data and print the R-squared score.

**Expected Output:** A single decimal number representing the R-squared score of the model.

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
r2_val=r2_score(y_test,y_pred)
print("R squared score is:",r2_val)

R squared score is: 0.5628903560152538

### Question 11: K-Means Clustering (5 Marks)

Import `KMeans` from `sklearn.cluster`. Initialize and fit the K-Means clustering model on the MNIST features (`X`).
Since we know there are 10 digits (0-9), set the number of clusters to 10. Assign the cluster labels to a variable `kmeans_labels`.

**Expected Output:** A successfully fitted K-Means model and the cluster labels array.

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=42)
kmeans.fit(X)
kmeans_labels = kmeans.labels_
kmeans_labels

array([1, 8, 5, ..., 6, 6, 6], dtype=int32)

In [ ]:
kmeans.cluster_centers_

array([[2.08699095e+00, 1.78892353e+03, 7.44932127e+00, 1.74762941e+03],
       [3.15586035e+00, 3.88717955e+03, 9.62967581e+00, 3.48200998e+03],
       [2.42156334e+00, 2.33662102e+03, 8.05876011e+00, 2.26977898e+03],
       [1.76322400e+00, 1.47689007e+03, 7.09663121e+00, 1.24293322e+03],
       [5.42045455e+00, 8.26454545e+03, 1.20000000e+01, 6.51727273e+03],
       [2.66509776e+00, 2.96700797e+03, 8.81390297e+00, 2.90078277e+03],
       [1.21689937e+00, 9.94916225e+02, 6.55657198e+00, 9.33186808e+02],
       [2.20642933e+00, 2.26301700e+03, 7.47980871e+00, 1.38296068e+03],
       [2.79597701e+00, 3.20260664e+03, 8.48786718e+00, 2.01869604e+03],
       [3.85491071e+00, 5.18303571e+03, 1.06696429e+01, 4.46321875e+03]])

### Question 12: F1 Score Evaluation for Clustering (5 Marks)

Evaluate the clustering performance using the F1 score. Since K-Means assigns arbitrary cluster labels, you will first need to map each cluster label to the most frequent true label in that cluster.
After mapping the labels, calculate and print the macro-averaged F1 score using `sklearn.metrics.f1_score`.

**Expected Output:** The calculated F1 score of the clustering.

In [ ]:
import numpy as np

mapped_labels = np.zeros_like(kmeans_labels)

for i in range(10):
    cluster_points = y[kmeans_labels == i]
    most_common_digit = np.bincount(cluster_points).argmax()
    mapped_labels[kmeans_labels == i] = most_common_digit
from sklearn.metrics import f1_score
print(f1_score(y, mapped_labels, average='macro'))

0.00014377052313772892

### Question 13: Confusion Matrix for Clustering (3 Marks)

Generate and display the confusion matrix comparing your mapped cluster labels (from Question 9) to the true labels (`y`). Use `confusion_matrix` from `sklearn.metrics`. This helps evaluate how well your clusters align with the actual digit classes without requiring visual plotting.

**Expected Output:** A 10x10 confusion matrix printed as an array or a Pandas DataFrame.